### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/daily-python-scripts#1]
### Is your feature request related to a problem? Please describe
With the new tech-boom and registration in multiple sites, people are running out of creating and managing unique passwords. Make a script, with a CLI which can be used to create unique password every time & also store them for later access.

### Describe the solution you'd like
Make a python script, with a CLI which can be used to create unique password every time & also store them for later access.

**Comment by Montekkundan** [comment]
please assign it to me! Can i also make a GUI for it?

**Comment by advaita-saha** [comment]
Sure go ahead
You can surely make a GUI for it

Do give some gifs in the readme then

Best of luck

**Comment by Montekkundan** [comment]
Thank you!

**Comment by Montekkundan** [comment]
## Is the GUI good?!

https://user-images.githubusercontent.com/87750128/192148443-51d80502-ab31-4d7b-868d-4ca71e647f85.mp4

**Comment by advaita-saha** [comment]
Yess great work @Montekkundan

**Comment by Montekkundan** [comment]
Should I send a pr today, will it be counted in hacktoberfest @advaita-saha ?

**Comment by Montekkundan** [comment]
#15 Completed!

**Comment by DanishAbdullahPy** [comment]
please assign it to me!

**Comment by Montekkundan** [comment]
@advaita-saha Hi, PRs made before 1st oct are not counted so can i close this pr and send one again?
