### ISSUE TITLE
YouTube video download by URL

### ISSUE THREAD

**Issue by akashJainAJ11** [metafy-social/daily-python-scripts#109]
### Is your feature request related to a problem? Please describe
Sometimes we need to download YouTube video in our local system.

### Describe the solution you'd like
we take URL of YouTube video by user and download video

**Comment by akashJainAJ11** [comment]
# Please assign this issue #109 to me
## i would like to work on it

**Comment by advaita-saha** [comment]
@akashJainAJ11 go ahead

**Comment by advaita-saha** [comment]
@akashJainAJ11 
Please add your email using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/

**Comment by akashJainAJ11** [comment]
@advaita-saha done 👍
