### ISSUE TITLE
Adding a table of all scripts with link, description and image/gif (if required) to them in README.md

### ISSUE THREAD

**Issue by Montekkundan** [metafy-social/daily-python-scripts#11]
### Is your feature request related to a problem? Please describe
Instead of finding all the scripts by going into the folder and reading about them from their individual readme we can have a table containing all details about a script with links to them.

#### Scripts
| Script Name                                                                                                                                 | Script detail            |Something else                                                                                                     |
|----------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|--------------------------------------------------------------------------------------------------------------------------|
| [Script 1](#) | `Does that`            | Something|
| [Script 2](#)     | `Does this`     | Something

**Comment by kriptonian1** [comment]
Would you like to work on this issue @Montekkundan

**Comment by Montekkundan** [comment]
sure!

**Comment by kriptonian1** [comment]
We at Metafy have some special rewards and swags for the top contributors in general repos and every contributor in web3 repos
For being eligible for that, please authenticate yourself using this link:
https://hacktoberfest.auth.metafy.social

Best of luck for Hacktoberfest
For further queries you can join our discord for support : https://discord.gg/W6PmEjjQsA

**Comment by bartick** [comment]
Please wait before working. This is a great feature about the repository we know. But this causes a lot of merge conflicts and people are not so much confident in using `git rebase` and might get too much stuck at merge conflicts. So we the the metafy team would like to discuss a little about it and will then assign it to you. Sorry for the inconvenience.
