### ISSUE TITLE
Computer stat checker

### ISSUE THREAD

**Issue by kriptonian1** [metafy-social/daily-python-scripts#12]
### Is your feature request related to a problem? Please describe
Let's see how your computer is doing, let's make a computer stat checker to see how your computer's CPU and RAM is doing.

### Describe the solution you'd like
Build a CPU and RAM checker to see how much resources is being used by your pc, and it would be pretty cool if it can also check the temperature for your pc

**Comment by mer747** [comment]
Hello @kriptonian1 I would like to be assigned for this issue!

**Comment by advaita-saha** [comment]
Sure go ahead @mer747

**Comment by mer747** [comment]
Thanks!

**Comment by advaita-saha** [comment]
@mer747 
Please add your email using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/

**Comment by mer747** [comment]
Sorry it is my first time contributing how can I do it @advaita-saha

**Comment by mer747** [comment]
I did it I guess

**Comment by advaita-saha** [comment]
> Sorry it is my first time contributing how can I do it @advaita-saha

In the auth link
Fill up the email field and click submit

**Comment by mer747** [comment]
Did it work?
