### ISSUE TITLE
Chatbot AI 🤖

### ISSUE THREAD

**Issue by kriptonian1** [metafy-social/daily-python-scripts#13]
### Is your feature request related to a problem? Please describe
We as developers are very lonely 😔 and mostly talk to our computer. Take this obsession one step further, and create a chatbot. IG that enough so explanation of why to create this one 🙂     

### Describe the solution you'd like
Create a chatbot to give our tormented soul some peace. Try to give it some personality too. For reference, use this [article](https://towardsdatascience.com/how-to-build-your-own-chatbot-using-deep-learning-bb41f970e281) , or watch this [youtube video](https://www.youtube.com/watch?v=UjDpW_SOrlw)

**Comment by Montekkundan** [comment]
Can i do this please 😄 !

**Comment by donheshanthaka** [comment]
Hey there, can you assign me for this issue.

**Comment by advaita-saha** [comment]
@donheshanthaka sure go ahead

**Comment by prajwal-144** [comment]
I would like to work on this issue. Can you please assign it to me.

**Comment by donheshanthaka** [comment]
@prajwal-144  hey there, actually i'm working on it :)

**Comment by agnxsh** [comment]
you can try as well, or maybe work with @donheshanthaka , okay @DanishAbdullahPy ?

**Comment by agnxsh** [comment]
@DanishAbdullahPy  you can work with @donheshanthaka too

**Comment by agnxsh** [comment]
@DanishAbdullahPy perhaps you can create a separate issue and work on it, maybe a chatbot with power apps, or with some more deep learning optimization?

**Comment by DanishAbdullahPy** [comment]
Hey i think i am very beginner at hacktoberfest so i will try create a separate issue and work on it
