### ISSUE TITLE
Exposed API Keys 

### ISSUE THREAD

**Issue by Rishav-12** [metafy-social/daily-python-scripts#131]
**Describe the bug**
There are exposed API keys in the Weather-Reports and the Weather-teller scripts.

**To Reproduce**
1. Go to `/daily-python-scripts/scripts/Weather_Reports/script.py` & `/daily-python-scripts/scripts/Weather-teller/weather-det.py`
2. See exposed API keys in the code

**Expected behavior**
The keys should not be in the file in plain text. It should ideally be read from a file or set as an environment variable.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by advaita-saha** [comment]
@Rishav-12 you want to work on fixing these??

**Comment by Icelain** [comment]
Hey I've written a quick fix for this just wanna know if the api keys currently being used should be added as environment variables through a shell script or that should be left to the user

**Comment by advaita-saha** [comment]
@Icelain 
https://github.com/metafy-social/daily-python-scripts/pull/26#issuecomment-1263936634

follow this approach
reply if you want to take this issue

**Comment by Icelain** [comment]
yeah i'd like to take this issue

**Comment by advaita-saha** [comment]
Go ahead @Icelain

**Comment by Icelain** [comment]
hey I've made the PR

**Comment by advaita-saha** [comment]
I do the requested changes

**Comment by Rishav-12** [comment]
> @Rishav-12 you want to work on fixing these??

Just filed an issue since its really not a good idea or a best practice to leave keys in plain sight. Great if @Icelain is working on this. 😃
