### ISSUE TITLE
some errors in text to speech code

### ISSUE THREAD

**Issue by lordvader501** [metafy-social/daily-python-scripts#135]
**Describe the bug**
want to add different accents in this code .
taking user input for text
the last line of os.system("mpg321 welcome.mp3") may not work on some pc. can add some alternattives to it.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/60027612/193994429-cdd75daa-149f-42c6-9dfd-709f1b031e1b.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/60027612/193994878-3507a315-06a1-49e6-be58-7d790db4038a.png">

**Comment by advaita-saha** [comment]
@lordvader501 go ahead
