### ISSUE TITLE
Text Based Adventure Game - Python

### ISSUE THREAD

**Issue by N00rAhmed** [metafy-social/daily-python-scripts#159]
### Describe the solution you'd like
I want to build a text adventure game which will give the user a story, options and items to choose from. In order to make this I will
be using the time library to create a delay when displaying story, random library to create selection of certain options at random and sys library which will be used to end program as a whole if user requests to quit the game .

### Describe alternatives you've considered
I considered creating a GUI using pygame or TKinter instead of having it print in the terminal but then I decided to keep it in the terminal as I want to make it as authentic as I can to a game which existed during the 1960's - 1970's.

### Additional context**
I would like to make this project for Hacktoberfest. This is a text adventure, purely for entertainment. This is going to be based of games which existed during the 1960's - 1970's like Zork I. The user will be given a story, options and items/tools to choose from.

**Comment by bartick** [comment]
@N00rAhmed  go ahead.

**Comment by advaita-saha** [comment]
@N00rAhmed 
Please add your email using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/

**Comment by N00rAhmed** [comment]
ok ive added my email.
