### ISSUE TITLE
Github CLI

### ISSUE THREAD

**Issue by shatanikmahanty** [metafy-social/daily-python-scripts#171]
### Is your feature request related to a problem? Please describe
I want to add a github stats viewer cli application. 

### Describe the solution you'd like
This solves the following pain points for developers:
- [x] No need to use heavy browsers to see stats used regularly
- [x] Use CLI to view user details

### Describe alternatives you've considered
There are small repos here and there but none that offers a comprehensive cli.

### Additional context**
None

**Comment by shatanikmahanty** [comment]
@bartick can you please assign this to me?

**Comment by advaita-saha** [comment]
@shatanikmahanty go ahead

**Comment by shatanikmahanty** [comment]
@advaita-saha I have a doubt. Can I improve my existing code by adding more functionalities over more PRs?

**Comment by bartick** [comment]
@shatanikmahanty sure create a new Issue describing your new functionality and wait for us to assign it to you. 
Then go ahead and open a new PR
