### ISSUE TITLE
Command line tool to check if servers/websites are up

### ISSUE THREAD

**Issue by Rishav-12** [metafy-social/daily-python-scripts#172]
### Is your feature request related to a problem? Please describe
One may want to check if their favourite websites or their servers are up and healthy

### Describe the solution you'd like
A simple script, which on being given a list of ip addresses or website URL's will ping them and report if they are up

### Describe alternatives you've considered
_None_

### Additional context**
_N/A_

**Comment by Rishav-12** [comment]
I would like to work on this, please

**Comment by Crazycoder122** [comment]
Can I be assigned this??
