### ISSUE TITLE
PDF to PPT converter.

### ISSUE THREAD

**Issue by Manice18** [metafy-social/daily-python-scripts#184]
### Is your feature request related to a problem? Please describe
It would be great to have a PDF to PPT converter if one wishes to make slides and add more templates to it.

### Describe the solution you'd like
Normally you can do the same by going to the web, but it would be great to have the script do it for you.

**Comment by Manice18** [comment]
I would like to work on this.

**Comment by bartick** [comment]
@Manice18 Go ahead

**Comment by royninja** [comment]
hi, can i work on this?

**Comment by royninja** [comment]
Hi can is it closed or if its still open can you assign this to me?

**Comment by Manice18** [comment]
@bartick u can close this issue ig.
