### ISSUE TITLE
Y Combinator News Ranking Script

### ISSUE THREAD

**Issue by raihankhan-rk** [metafy-social/daily-python-scripts#189]
### Is your feature request related to a problem? Please describe
The YCombinator News section is one of the best news section when it comes to the latest tech news, but however, the algorithm does not rank the news in any sort. It just shows the latest news. This makes it difficult for users who are running short on time. 

### Describe the solution you'd like
The script will scrape the website and rank the news based on the number of likes.

**Comment by bartick** [comment]
@raihankhan-rk go ahead

**Comment by raihankhan-rk** [comment]
Added YCombinator News Ranking Script #219
