### ISSUE TITLE
Website Blocker Script

### ISSUE THREAD

**Issue by kriptonian1** [metafy-social/daily-python-scripts#2]
**Is your feature request related to a problem? Please describe.**
Create an application to block websites of user's choice. 

**Describe the solution you'd like**
Use python to make a website blocker that stops users from going to a website you don't want them to go to. Websites can be added or removed by the admin only. 

**Please comment your approach towards this, and we are happy to assign this to you**

**Comment by Montekkundan** [comment]
please assign it to me!

**Comment by advaita-saha** [comment]
Go ahead @Montekkundan

**Comment by Montekkundan** [comment]
Thank you!

**Comment by Montekkundan** [comment]
@advaita-saha @kriptonian1 Hi, PRs made before 1st oct are not counted so can i close this pr and send one again?
