### ISSUE TITLE
EMPLOYEE MANAGEMENT SYSTEM

### ISSUE THREAD

**Issue by Shradha-Suman** [metafy-social/daily-python-scripts#202]
### Is your feature request related to a problem? Please describe

In big companies a large database of employees is to be maintained, so instead of doing data entries into excel file which can be time consuming. we can directly use queries to do so.

### Describe the solution you'd like
I want to write a python program using queries that deals with the above problem.

### Describe alternatives you've considered
we can use different databases available with python and I consider python for the above purpose because I find it to be bit easier and understandable language for large programs.

**Comment by Shradha-Suman** [comment]
please review this issue...

**Comment by advaita-saha** [comment]
Go ahead @Shradha-Suman
