### ISSUE TITLE
Python project to track Amazon prices

### ISSUE THREAD

**Issue by ighoshsubho** [metafy-social/daily-python-scripts#204]
### Is your feature request related to a problem? Please describe
I have often suffered while buying a product from amazon at right time and therefore want to make this project to solve my problem

### Describe the solution you'd like
Thy python app will keep track of amazon products and  send us mail when prices will go down.

**Comment by advaita-saha** [comment]
Go ahead @ighoshsubho

**Comment by advaita-saha** [comment]
@ighoshsubho 
Please add your email using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/
