### ISSUE TITLE
Encrypted Password Manager Using Tkinter and Symmetric Encrytion

### ISSUE THREAD

**Issue by parinzee** [metafy-social/daily-python-scripts#205]
### Is your feature request related to a problem? Please describe
I'm frustrated by the need to use online password managers and really wanted to provide people with a secure offline-based solution!

### Describe the solution you'd like
Created a simple GUI for an encrypted password manager using a Symmetric Encryption

I'll begin work on this right away!

**Comment by advaita-saha** [comment]
@parinzee it is already there
