### ISSUE TITLE
Password Security level Checker

### ISSUE THREAD

**Issue by Abbhiishek** [metafy-social/daily-python-scripts#21]
### Is your feature request related to a problem? Please describe
Password Security level Checker

### Describe the solution you'd like
A python Script which takes a Password as input and compute how much secure the string is between the scale of 1 to 10.

### Describe alternatives you've considered
What we can do else is compare the password with set of instruction and find the flaws

**Comment by advaita-saha** [comment]
Sure go ahead @Abbhiishek

**Comment by advaita-saha** [comment]
Do comment your approach once here in the issues @Abbhiishek

**Comment by priddhesh** [comment]
Please assign me this task.I would like to contribute.

**Comment by advaita-saha** [comment]
> Please assign me this task.I would like to contribute.

Please check before commenting,
This issue is already assigned

**Comment by priddhesh** [comment]
Yes, I know it is assigned.I thought multiple people can be assigned.Will it be ok if I work on this issue?

**Comment by Abbhiishek** [comment]
@advaita-saha 

Well I am thinking of doing this in two different ways.
1. Include a python Package that will check for me the strength of the password.
2. Secondly , is to create a class and create some methods to check that.


This way we can also publish the code to PyPI and have our own package

**Comment by advaita-saha** [comment]
Ok good
