### ISSUE TITLE
Link not proper

### ISSUE THREAD

**Issue by Manice18** [metafy-social/daily-python-scripts#22]
![image](https://user-images.githubusercontent.com/91601706/192553636-9e2c4a64-c38c-4e63-888d-a116f9c48c44.png)
the link is not proper in the daily-python scripts' Readme.md file.

**Comment by Manice18** [comment]
![image](https://user-images.githubusercontent.com/91601706/192554007-6e70698a-1928-4a40-8b26-a16767294e2f.png)
its leading here

**Comment by advaita-saha** [comment]
Thank you for pointing out this issue, our team will be looking on this soon

**Comment by advaita-saha** [comment]
@bartick 
Solve this internal error ASAP
