### ISSUE TITLE
A Full fledged Password Manager App with Tkinter 

### ISSUE THREAD

**Issue by raihankhan-rk** [metafy-social/daily-python-scripts#220]
### Is your feature request related to a problem? Please describe
It's often a struggle to remember different passwords for different websites.

### Describe the solution you'd like
A full-fledged Password Manager App that stores the user's password along with the username and the website. It also offers a feature to randomly generate passwords for users.

**Comment by advaita-saha** [comment]
@raihankhan-rk go ahead

**Comment by raihankhan-rk** [comment]
@advaita-saha I've added the password manager app. Kindly approve PR #228
