### ISSUE TITLE
A Script to detect and translate to any language using speech recognition

### ISSUE THREAD

**Issue by Tejaswi-Kumar** [metafy-social/daily-python-scripts#221]
### Is your feature request related to a problem? Please describe
Most of the time, people have to use google's translation API, which has a limited amount of requests for translation between languages. But python has a free-of-charge library that is accurate enough and can do the same task efficiently.

### Describe the solution you'd like
A python script that first records the user's voice and then converts it to text. After that, it detects the language of the text and then translates the language to the user's desired language, which is asked of the user.

### Additional context**
Some advanced libraries which need to be installed before running the program would be a prerequisite for the script

**Comment by agnxsh** [comment]
go for it @Tejaswi-Kumar
