### ISSUE TITLE
Pomodoro App

### ISSUE THREAD

**Issue by raihankhan-rk** [metafy-social/daily-python-scripts#230]
### Is your feature request related to a problem? Please describe
Focusing while studying is a big challenge.

### Describe the solution you'd like
Pomodoro is a technique used in many foreign countries to increase focus and productivity by breaking the time slot into 25mins work and 5mins break

**Comment by advaita-saha** [comment]
@raihankhan-rk go ahead

**Comment by raihankhan-rk** [comment]
@advaita-saha I've added the Pomodoro App. Kindly approve PR #233
