### ISSUE TITLE
Google images download

### ISSUE THREAD

**Issue by Hemant2801** [metafy-social/daily-python-scripts#234]
### Is your feature request related to a problem? Please describe
While you want to create a large dataset of images for you ML model it becomes hectic to download images one by one. This will help in downloading the images in bulk.

### Describe the solution you'd like
This code will ask for two thing the name of the object and the amount of images to download.

### Describe alternatives you've considered
An alternative to this code is to create a new web scrapping code that scraps google for images.

**Comment by advaita-saha** [comment]
@Hemant2801 go ahead

**Comment by bartick** [comment]
Invalid PR
