### ISSUE TITLE
Stock Alert Script

### ISSUE THREAD

**Issue by raihankhan-rk** [metafy-social/daily-python-scripts#235]
### Is your feature request related to a problem? Please describe
It's a struggle to constantly monitor Stock prices

### Describe the solution you'd like
This script constantly monitors user favorite stocks and sends an email alert whenever the stock's prices deflect by a greater margin.

**Comment by advaita-saha** [comment]
@raihankhan-rk go ahead

**Comment by raihankhan-rk** [comment]
@advaita-saha I've added the Stock Alert App. Please kindly approve PR #240
