### ISSUE TITLE
GrammarX tool - python script which finds and correct grammar mistakes from text file

### ISSUE THREAD

**Issue by LEO1612D** [metafy-social/daily-python-scripts#237]
### Is your feature request related to a problem? Please describe
I often face this problem of grammatical mistakes in my text, emails or any other places, also if you are student and you want to check any grammar mistakes in your essay or writing sometimes online tools are hard to correct all mistakes.

### Describe the solution you'd like
I have created this easy scripting tool which will help us to achieve this, called GrammarX, this tool will automatically display all the corrected mistakes from your text, essay or anything else. 

### Describe alternatives you've considered
Alternatives are [Grammarly](https://app.grammarly.com/) online

**Comment by advaita-saha** [comment]
@LEO1612D go ahead

**Comment by advaita-saha** [comment]
@LEO1612D 
Please add your email using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/

**Comment by LEO1612D** [comment]
> @LEO1612D Please add your email using the authentication link Or else we won't be able to send you the amazing rewards you deserve
> 
> https://hacktoberfest.auth.metafy.social/

Okay sure.
