### ISSUE TITLE
Wallpaper Engine

### ISSUE THREAD

**Issue by raihankhan-rk** [metafy-social/daily-python-scripts#249]
### Is your feature request related to a problem? Please describe
It's a struggle to find the perfect wallpaper for your PC.

### Describe the solution you'd like
This is a python script that automatically fetches and downloads wallpaper for the user as per his preference.

**Comment by advaita-saha** [comment]
@raihankhan-rk go ahead

**Comment by raihankhan-rk** [comment]
@advaita-saha I've added the Wallpaper Engine Script. Kindly approve PR #254
