### ISSUE TITLE
Email Extractor from a webpage

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/daily-python-scripts#253]
### Is your feature request related to a problem? Please describe
Emails are required for marketing, but are hard to acquire 

### Describe the solution you'd like
A simple email scraping script using python, to get all the emails present in a webpage

**Comment by royninja** [comment]
you want  the gathered email inside a file?

**Comment by atharvai812** [comment]
Assign me

**Comment by advaita-saha** [comment]
> you want the gathered email inside a file?

yes

**Comment by royninja** [comment]
> > you want the gathered email inside a file?
> 
> yes

assign me

**Comment by atharvai812** [comment]
#255

**Comment by advaita-saha** [comment]
@royninja go ahead
