### ISSUE TITLE
Mood based movie recommendation API

### ISSUE THREAD

**Issue by codeswithroh** [metafy-social/daily-python-scripts#257]
### Is your feature request related to a problem? Please describe
A lot of times people gets confused about what movie to watch. A lot of bickering among friends, spats between lovers happen because of movie decisions. So, my script address this problem.

### Describe the solution you'd like
My solution is simple. It would ask you for your mood and based on your mood the api will suggest you movies so, that you don't need to think hard for which movie to watch.

**Comment by advaita-saha** [comment]
go ahead @codeswithroh

**Comment by prajwal-144** [comment]
Hey, I would like to work on this issue.
Can you assign it to me please?
