### ISSUE TITLE
Message Encoder and Decoder

### ISSUE THREAD

**Issue by iamrahul8** [metafy-social/daily-python-scripts#266]
### Is your feature request related to a problem? Please describe
A web application used to encrypt and decrypt text messages. For the encodings listed in RFC 4648, it offers encoding and decoding functions.

### Describe the solution you'd like
It will encode a message ( that is secret ) , and sender will able to send anyone without revealing his/her privacy.

### Describe alternatives you've considered
Teck stack used : 
- Python 
- Streamlit

> I want to work on this , please assign me under `hacktoberfest`

**Comment by advaita-saha** [comment]
@iamrahul8 go ahead
