### ISSUE TITLE
Internet Speed Checker ⏩

### ISSUE THREAD

**Issue by Abbhiishek** [metafy-social/daily-python-scripts#27]
### Is your feature request related to a problem? Please describe
It's always frustrating to surf the internet to find the network speed we are getting.

### Describe the solution you'd like
Will use a script to check the internet speed with build package published in PyPI.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/86338762/193392592-d14b5383-8c80-481e-9eed-2328e6a378be.png">

Kindly assign ✨

**Comment by advaita-saha** [comment]
Sure go ahead @Abbhiishek

**Comment by atharva360** [comment]
can i get this task?
