### ISSUE TITLE
Compressing images using python

### ISSUE THREAD

**Issue by MSVelan** [metafy-social/daily-python-scripts#284]
### Is your feature request related to a problem? Please describe
There are many times we require images to be compressed. We can use this program to do that and it can reduce 2.5 Mb image to just 293 kb 
### Describe the solution you'd like
I would like to use the pillow library in python for implementation.

**Comment by bartick** [comment]
Sorry I don't see the need of this script. Pillow already have a build in flag to optimize a image size
