### ISSUE TITLE
Internet Speed Tester

### ISSUE THREAD

**Issue by dishant-yadav** [metafy-social/daily-python-scripts#289]
### Is your feature request related to a problem? Please describe
A simple utility in **Python** to check the **internet speed of a network**.

### Describe the solution you'd like
I will be using the [**speedtest**](https://github.com/sivel/speedtest-cli) library in python.

### Describe alternatives you've considered
The utility will be return the **upload, download and ping** of a network.

**Comment by bartick** [comment]
Not exactly sure about this script. So can you also create a GUI to make it more appealing?  @dishant-yadav

**Comment by ArshErgon** [comment]
assign this to me

**Comment by dishant-yadav** [comment]
> Not exactly sure about this script. So can you also create a GUI to make it more appealing? @dishant-yadav
Yeah sure I can create a GUI for the same. @bartick

**Comment by bartick** [comment]
@dishant-yadav go ahead

**Comment by dishant-yadav** [comment]
Thanks for assigning me the issue.

**Comment by mdzeeshan-2** [comment]
Please assign this to me

**Comment by 035pratheeksha** [comment]
Please assign this to me

@bartick
