### ISSUE TITLE
Image Compressor

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/daily-python-scripts#3]
### Is your feature request related to a problem? Please describe
In a lot of different places while uploading pics we get an error, that the file size limit exceeded. This created a lot of mess and we somehow have to crop the image, and make it suitable

### Describe the solution you'd like
Make a CLI based image compressor. It should take the image file path as a command-line argument, and then store the compressed file as **"compressed-<file_name>.<extension>"**

**Comment by priddhesh** [comment]
@bartick  @advaita-saha please assign me this task

**Comment by bartick** [comment]
@priddhesh assigned go ahead and start coding.

**Comment by priddhesh** [comment]
@kriptonian1 I am unable to raise new PR for this issue.What should I do??

**Comment by priddhesh** [comment]
@kriptonian1 
![image](https://user-images.githubusercontent.com/109747774/192155538-f730a7ee-bd4d-4c2b-8312-757b16389193.png)
Image Compressor files got added to the previous PR

**Comment by kriptonian1** [comment]
@priddhesh have you tagged this issue number to your PR

**Comment by priddhesh** [comment]
no

**Comment by priddhesh** [comment]
Actually there is no option for new pull request.All these files are being added to previous PR.
