### ISSUE TITLE
Linear Regression Project added to find linear relation between two related variables

### ISSUE THREAD

**Issue by NebulaAnish** [metafy-social/daily-python-scripts#327]
### Is your feature request related to a problem? Please describe
I wanted to find some relation between the variables. For eg when I want to approximate expected gross income from a movie based on it's budget, then I can use it to analyze the past records and hence find an approximation.

### Describe alternatives you've considered
This can be achieved by several web based applications but i wanted to make use of my programming skills and make some use out of it.
### Additional context**
This is not primarily for a use case but rather for the learning process, yet it does it's job well.

**Comment by Sengar123** [comment]
Hello,Kindly assign this task to me.I want to contribute into this issue.
