### ISSUE TITLE
Want to add a dictionary GUI project in Python

### ISSUE THREAD

**Issue by KuSantosh100** [metafy-social/daily-python-scripts#338]
### Is your feature request related to a problem? Please describe
Instead of flipping pages from BIG Oxford Dictionary or Googling the meaning of the words
which obviously requires an internet connection let's search it using python code.

### Describe the solution you'd like
I made a dictionary program that searches the meanings of the words from the PyDictonary library.
On top of that, I added a simplistic GUI using Tkinter.

**Comment by KuSantosh100** [comment]
Can anyone assign me this task? @bartick  @advaita-saha

**Comment by bartick** [comment]
@KuSantosh100 sure go ahead

**Comment by KuSantosh100** [comment]
Thank You Very Much @bartick  for the opportunity.
