### ISSUE TITLE
Add Confusion Matrix

### ISSUE THREAD

**Issue by lucasocarvalhos** [metafy-social/daily-python-scripts#359]
### Is your feature request related to a problem? Please describe
Methods to measure the perfomance of ML models are very important. A confusion matrix is a very good way to visualize the performance of a machine learning classification problem.

### Describe the solution you'd like
This is a function useful to create a pretty confusion matrix. It is extremely useful for measuring Recall, Precision, Specificity, Accuracy, and most importantly AUC-ROC curves.

**Comment by advaita-saha** [comment]
@lucasocarvalhos go ahead
