### ISSUE TITLE
Hangman Game In Python

### ISSUE THREAD

**Issue by SuvarneshKM** [metafy-social/daily-python-scripts#407]
### Describe the solution you'd like
A Hangman Game is about guessing letters (A-Z) to form the words.

### Describe alternatives you've considered
 If the player guesses the right letter that is within the word, the letter appears at its correct position. The user has to guess the correct word until a man is hung, then the game is over.

**Comment by bartick** [comment]
Sorry can't see the use of it. Also its very easily available on the internet
