### ISSUE TITLE
Extract text from PDF 

### ISSUE THREAD

**Issue by anjali1102** [metafy-social/daily-python-scripts#41]
### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. Most companies have a collection of PDF documents they would like to extract data from.

### Describe the solution you'd like
using PyPDF2 package

**Comment by advaita-saha** [comment]
Sure go ahead @anjali1102

**Comment by atharva360** [comment]
can i get this task?

**Comment by anjali1102** [comment]
I am working on it rn
