### ISSUE TITLE
Feature Request :  Img  to Png coverter in python

### ISSUE THREAD

**Issue by SiddheshKukade** [metafy-social/daily-python-scripts#45]
### Is your feature request related to a problem? Please describe
there is not any img to png converter available here

### Describe the solution you'd like
I would like to add a script to convert .jpg images to .png images format
### Additional context**
I  can also remove background if required

**Comment by atharva360** [comment]
can i get this task please?

**Comment by SiddheshKukade** [comment]
@atharva360 no I am working on  it
