### ISSUE TITLE
Feature Request : Adding a Automation Script to translate contents of txt file from one language to another

### ISSUE THREAD

**Issue by SiddheshKukade** [metafy-social/daily-python-scripts#46]
### Is your feature request related to a problem? Please describe
There is not any  Automation Script avaialble to translate contents of txt file from one language to another
### Describe the solution you'd like
To add a python script for  Automation Script to translate contents of txt file from one language to another

### Please assign me this issue

**Comment by advaita-saha** [comment]
Nice go ahead @SiddheshKukade
