### ISSUE TITLE
URL Shortner Script

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/daily-python-scripts#5]
### Is your feature request related to a problem? Please describe
While sharing links from different websites, it gets pretty long and difficult to share and understand

### Describe the solution you'd like
Make a CLI based program that can take input of the link, and give a shortened version of the link. You are free to use any API which is FREE.

### Please comment your approach towards this, and we are happy to assign this to you

**Comment by priddhesh** [comment]
Hello @advaita-saha I can build YouTube URL shortner using HTML,CSS and JS.Please assign me.Thank You.

**Comment by bartick** [comment]
@priddhesh this is a python repo 🤦.
If you doing it in python we are happy to assign you the issue

**Comment by priddhesh** [comment]
Yes I can do it in python using bitly_api.You can assign me.

**Comment by advaita-saha** [comment]
Sure you can go ahead
Make sure you do create a CLI

**Comment by priddhesh** [comment]
Is it necessary to create CLI as I have no experience about it..??

**Comment by advaita-saha** [comment]
Yes, it is very easy just google about it
You can learn it in the process

It is nothing, just taking input and showing output in the command line

**Comment by priddhesh** [comment]
Okay I will do that.

**Comment by priddhesh** [comment]
I got it.

**Comment by priddhesh** [comment]
Will these pull requested be merged (if correct) after hacktoberfest start??

**Comment by advaita-saha** [comment]
Yess it will be merged @priddhesh

**Comment by priddhesh** [comment]
I am ready with code

**Comment by advaita-saha** [comment]
go ahead and create a PR

**Comment by priddhesh** [comment]
But if you merge it now then it will no be considered for hacktoberfest

**Comment by priddhesh** [comment]
> go ahead and create a PR

But if you merge it now then it will no be considered for hacktoberfest

**Comment by bartick** [comment]
@priddhesh open the PR after/on 1st of October.

**Comment by priddhesh** [comment]
> @priddhesh open the PR after/on 1st of October.

Yes, sure

**Comment by advaita-saha** [comment]
@priddhesh 
We at Metafy have some special rewards and swags for the top contributors in general repos and every contributor in web3 repos
For being eligible for that, please authenticate yourself using this link:
https://hacktoberfest.auth.metafy.social

Best of luck for Hacktoberfest
For further queries you can join our discord for support : https://discord.gg/W6PmEjjQsA
