### ISSUE TITLE
PNG to PDF converter

### ISSUE THREAD

**Issue by Farhan-2222** [metafy-social/daily-python-scripts#50]
### Is your feature request related to a problem? Please describe
I don't see any script in this repository which converts PNG to PDF.
### Describe the solution you'd like
I would like to add a png to pdf converter here.

**Comment by advaita-saha** [comment]
@Farhan-2222 go ahead

**Comment by Farhan-2222** [comment]
This is my first contribution. Just want to know when will my code be added to the main repository.
