### ISSUE TITLE
Enhance Documentation | README.md

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/daily-python-scripts#6]

**Comment by Montekkundan** [comment]
Adding gifs and custom logo would look good.

**Comment by aswin2108** [comment]
I would love to add the contributors list in the readme file and automate it with github actions! would love to do it

**Comment by advaita-saha** [comment]
Sure go ahead @aswin2108

**Comment by advaita-saha** [comment]
This issue have already been assigned to @aswin2108 
If you want to contribute something different feel free to create a new issue @Montekkundan
