### ISSUE TITLE
RGB to Hexadecimal

### ISSUE THREAD

**Issue by Farhan-2222** [metafy-social/daily-python-scripts#65]
### Is your feature request related to a problem? Please describe
There isn't a code in this repository that converts RGB to hex value.
### Describe the solution you'd like
A RGB to Hex converter using python programming

**Comment by advaita-saha** [comment]
Go ahead @Farhan-2222

**Comment by Farhan-2222** [comment]
Thanks but this isn't my first commit in this repository.😅 Hope to make many more contribution.
