### ISSUE TITLE
Screenshots Tool

### ISSUE THREAD

**Issue by kriptonian1** [metafy-social/daily-python-scripts#7]
### Is your feature request related to a problem? Please describe
It's always handy to have an easy-to-use screenshot tool. 

### Describe the solution you'd like
Make an easy-to-use screenshot tool with all modern features like click a selected screen space. You can use modules like `pyscreenshot` to make the application.

**Comment by bartick** [comment]
@ArshErgon we are not allowing self assign feature. If you want to take this issue. Just say so and we will assign it to you.

**Comment by ArshErgon** [comment]
@bartick sure, could you please assign it to me?

**Comment by bartick** [comment]
@ArshErgon assigned. Please go ahead and start coding

**Comment by ArshErgon** [comment]
I have add the code which is need

**Comment by bartick** [comment]
Well done. We will accept it after hacktoberfest has started. So this contribution gets counted towards your goal. Just make sure you are registered as a contributor. 
Registration starts from 26th of September on the official hacktoberfest website

**Comment by ArshErgon** [comment]
thank you so much, and yeah I'm registered, thanks again

**Comment by advaita-saha** [comment]
@ArshErgon 
We at Metafy have some special rewards and swags for the top contributors in general repos and every contributor in web3 repos
For being eligible for that, please authenticate yourself using this link:
https://hacktoberfest.auth.metafy.social/

Best of luck for Hacktoberfest
For further queries you can join our discord for support : https://discord.gg/W6PmEjjQsA
