### ISSUE TITLE
enhancement : To convert a list of images to PDF

### ISSUE THREAD

**Issue by artemis-i-guess** [metafy-social/daily-python-scripts#71]
### Is your feature request related to a problem? Please describe

There are only examples of how to convert a single image to pdf. But we may be required to include multiple images of any extension to be converted to pdf. Hence I would like to introduce a script where I will include various images of .png or .jpg extention and make a single PDF.

### Describe the solution you'd like

To add a python script to do the same .

**Comment by artemis-i-guess** [comment]
please assign :)

**Comment by advaita-saha** [comment]
@artemis-i-guess 

You work on enhancing the the script to your proposition 
https://github.com/metafy-social/daily-python-scripts/tree/master/scripts/PNG_To_PDF

**Comment by vatsal9117** [comment]
hey i love to contribute please assign me
