### ISSUE TITLE
Automated QR code generator.

### ISSUE THREAD

**Issue by Dishant10** [metafy-social/daily-python-scripts#80]
### Is your feature request related to a problem? Please describe
With this program or script we can easily create a QR code from any web link. That will help us to use the QR code in any given situation that is easy to make as many as you want.

### Describe the solution you'd like
I want to make a python program which takes a web url and converts that link to a QR code in png format.

### Describe alternatives you've considered
We can also generate a QR code using online websites but creating using our own skills is something magical and will strengthen our python knowledge too.

**Comment by Dishant10** [comment]
I would love to work on this issue I created. I have some more ideas for which I'll create more issues.
Do let me know if you'd  like to approve it and any suggestions from your side are always welcomes I'll try to incorporate that as well.

**Comment by advaita-saha** [comment]
@Dishant10 go ahead

**Comment by advaita-saha** [comment]
Please complete the readme file

**Comment by Dishant10** [comment]
I hoped this issue was assigned to me. And this repo gives 3 weeks of time to create a PR. Anyway I'm also creating another issue. I hope I get some time to create a PR.

**Comment by advaita-saha** [comment]
@Dishant10 
I am actually very sorry, both me and my team have missed this
We strongly are against these type of actions

Do drop us an email at support@metafy.social . We will try our best how we can help you 

Feel free to raise a issue, and we are flagging @akashJainAJ11

**Comment by Dishant10** [comment]
No issues. Let it be now. I will add more stuff by creating more issues. B

**Comment by akashJainAJ11** [comment]
@Dishant10 I am very sorry. I did not notice that.
@advaita-saha

**Comment by Dishant10** [comment]
@advaita-saha should I create more issues to add new scripts ? I already have one please assign it to me so that I can start working on it.
