### ISSUE TITLE
RGB to Grayscale

### ISSUE THREAD

**Issue by muratonuryildirim** [metafy-social/daily-python-scripts#82]
### Is your feature request related to a problem? Please describe
Converting RGB images to grayscale is necessary for some problems and it supports to compress memory and fasten the processing.

### Describe the solution you'd like
A script or a function that can convert RGB images to grayscale would be beneficial for both daily and professional work.

### Describe alternatives you've considered
Building a function that do not require lots of dependencies to provide a easy to use tool.

### Additional context**
Could you please assign me to that?

**Comment by HVbajoria** [comment]
Hello, 
Could you please assign me this issue.

**Comment by muratonuryildirim** [comment]
Could you please assign me to mine issue @advaita-saha :)

**Comment by advaita-saha** [comment]
@bartick have a look please

**Comment by bartick** [comment]
@muratonuryildirim sure go ahead
