### ISSUE TITLE
pickle to txt or json

### ISSUE THREAD

**Issue by muratonuryildirim** [metafy-social/daily-python-scripts#88]
### Is your feature request related to a problem? Please describe
Pickle implements binary protocols for serializing and de-serializing a Python object structure. It can be hard to read and only used in python. 

### Describe the solution you'd like
I would like to create a function  that converts pickle files to more readable and accessible .txt or .json files.

### Additional context**
Could you please assign me that issue :)

**Comment by muratonuryildirim** [comment]
Could you please assign me that issue  @advaita-saha :)

**Comment by advaita-saha** [comment]
@bartick @kriptonian1 
Please have a look whether it is relevant or not

**Comment by bartick** [comment]
@muratonuryildirim go ahead. 
Sorry for the delay I wasn't available for few days. Your idea would be a great addition to this repo.
