### ISSUE TITLE
Fidget Spinner

### ISSUE THREAD

**Issue by HVbajoria** [metafy-social/daily-python-scripts#92]
I wish to add a Fidget Spinner Simulator script in Python. 

### Describe the solution you'd like
I wish to add a Fidget Spinner Simulator made using Python that will help everyone have some fun time. 

### Additional context
Could you please assign me the issue so that I can contribute. 

Happy HacktoberFest!

**Comment by advaita-saha** [comment]
@HVbajoria go ahead
