### ISSUE TITLE
Slice mp3 files into smaller portions 

### ISSUE THREAD

**Issue by Dishant10** [metafy-social/daily-python-scripts#97]
### Is your feature request related to a problem? Please describe
We always wanted to have only a particular part of an audio/mp3 file. This python script does exactly for you.

### Describe the solution you'd like
This python program slices a portion of an audio file of a specific length according to the user and will also save at a particular path which also can be controlled by the user itself.

### Describe alternatives you've considered
We have to use online websites in which the process is usually cumbersome.

### Additional context**
Just add your file path and your export path along with the duration you want to cut the audio file. The rest is magic. Check your export path a new file would be there.

**Comment by Dishant10** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by Dishant10** [comment]
@advaita-saha I'd really appreciate if you'd approve on this one.

**Comment by advaita-saha** [comment]
@Dishant10 Go ahead

**Comment by Dishant10** [comment]
Sure! Thanks.
