### ISSUE TITLE
PDF to Voice 

### ISSUE THREAD

**Issue by yashbrid03** [metafy-social/daily-python-scripts#99]
Python Script to convert PDF to Voice

**Comment by advaita-saha** [comment]
@yashbrid03 
Please add your email using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/

**Comment by yashbrid03** [comment]
> @yashbrid03 Please add your email using the authentication link Or else we won't be able to send you the amazing rewards you deserve
> 
> https://hacktoberfest.auth.metafy.social/

What should i add in metamask account address?

**Comment by yashbrid03** [comment]
> @yashbrid03 Please add your email using the authentication link Or else we won't be able to send you the amazing rewards you deserve
> 
> https://hacktoberfest.auth.metafy.social/

Done
